name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Translate secrets of base64 into json
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo $GOOGLE_SERVICE | base64 --decode > ./JobCareer/output.json

    - name: Translate json into plist and generate GoogleService-info.plist
      run: plutil -convert xml1 ./JobCareer/output.json -o ./JobCareer/GoogleService-info.plist

    - name: Remove json file
      run: rm JobCareer/output.json

    - name: Cache Swift Packages
      uses: actions/cache@v1
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-

    - name: Build
      run: xcodebuild
        -scheme JobCareer
        -sdk iphonesimulator
        -configuration Debug
        build

      # -clonedSourcePackagesDirPath SourcePackages

    - name: Run tests
      run: xcodebuild
        -scheme JobCareer
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 13'
        clean test
