name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Translate secrets of base64 into GoogleService-info.json
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo $GOOGLE_SERVICE | base64 --decode > ./JobCareer/GoogleService-info.json

    - name: Translate json into plist and generate GoogleService-info.plist
      run: plutil -convert xml1 ./JobCareer/GoogleService-info.json -o ./JobCareer/GoogleService-info.plist

    - name: Remove Json file
      run: rm JobCareer/GoogleService-info.json

      # Swiftプロジェクトのビルドの高速化
    - name: Enable faster builds for Swift projects
      run: defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1

    - name: Cache Swift Packages
      uses: actions/cache@v1
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-

    - name: Build
      run: xcodebuild
        -scheme JobCareer
        -sdk iphonesimulator
        -configuration Debug
        -clonedSourcePackagesDirPath SourcePackages
        build

    - name: Run tests
      run: xcodebuild
        -scheme JobCareer
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 13'
        clean test
